services:
  - type: web
    name: teaching-schedule-app
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Hệ Thống Lịch Giảng Dạy"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: teaching-schedule-app
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: "teaching_schedule"
      - key: DB_USERNAME
        value: "iAz3Sb8PKvwUN1D.root"
      - key: DB_PASSWORD
        value: "Tl5nqVfJF5UpSw3K"
      - key: MYSQL_ATTR_SSL_CA
        value: "/etc/ssl/certs/ca-certificates.crt"
      - key: SESSION_DRIVER
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stderr
